const PRIVATE_MESSAGE_SOCKET = 'PRIVATE_MESSAGE_SOCKET';
const GROUP_MESSAGE_SOCKET = 'GROUP_MESSAGE_SOCKET';
const GLOBAL_MESSAGE_SOCKET = 'GLOBAL_MESSAGE_SOCKET';

module.exports = {
  PRIVATE_MESSAGE_SOCKET,
  GROUP_MESSAGE_SOCKET,
  GLOBAL_MESSAGE_SOCKET
};
