const SEND_MESSAGE_SOCKET = 'SEND_MESSAGE_SOCKET';
const GIVE_CHAT_SOCKET = 'GIVE_CHAT_SOCKET';
const CREATE_CHAT_SOCKET = 'CREATE_CHAT_SOCKET';

module.exports = {
  SEND_MESSAGE_SOCKET,
  GIVE_CHAT_SOCKET,
  CREATE_CHAT_SOCKET
};
